### ISSUE TITLE
点击连接直接闪退... 

### ISSUE THREAD

**Issue by mox113** [LiuJunb/ActiveMQ-MQTT-Android#1]
换了我们自己的mq地址，但...

**Comment by zfcjava** [comment]
我也遇到相同的错误了， 能帮忙解决一下吗，谢谢

09-04 17:31:18.751 23958-23998/activemq.xmg.com.activemq_mqtt E/AndroidRuntime: FATAL EXCEPTION: MQTT Con: liujun
    Process: activemq.xmg.com.activemq_mqtt, PID: 23958
    java.lang.NullPointerException: cancel() called with a null PendingIntent
        at android.app.AlarmManager.cancel(AlarmManager.java:892)
        at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:327)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:608)
        at java.lang.Thread.run(Thread.java:776)

**Comment by TTLZZU** [comment]
Android 22,23,24,25，使用mqttClient均可以连接上ActiveMQ，使用Andriod 27,28,
始终连接不上，报异常：| Transport Connection to: tcp://192.168.2.160:49506 failed: java.io.EOFException
